spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/userservice/**
            
        - id: favourite-service
          uri: lb://favourite-service
          predicates:
            - Path=/api/news/**           
       
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    
server:
  port: 9001
  
